lab6test: lab_6_unit_test.o lab_6.o
	g++ -Wall -g -o lab6test lab_6.o lab_6_unit_test.o
	
lab6: lab_6.cpp lab_6.h
	g++ -Wal -g -o lab_6.cpp
	
lab_6_unit_Test: lab_6_unit_test.cpp
	g++ -Wall -g -c lab_6_unit_test.cpp