lab22test: lab_22_unit_test.o bst_node.o bs_tree.o
	g++ -Wall -g -o lab22test lab_22_unit_test.o bst_node.o bs_tree.o

lab_22_B: bs_tree.cpp bs_tree.h
	g++ -Wall -g -c bs_tree.cpp

lab_22_A: bst_node.cpp bst_node.h
	g++ -Wall -g -c bst_node.cpp

lab_22_unit_test: lab_22_unit_test.cpp 
	g++ -Wall -g -c lab_22_unit_test.cpp