lab8test: lab_8_unit_test.o lab_7.o
	g++ -Wall -g -o lab8test lab_7.o lab_8_unit_test.o

lab7test: lab_7_unit_test.o lab_7.o
	g++ -Wall -g -o lab7test lab_7.o lab_7_unit_test.o
	
lab7: lab_7.cpp lab_7.h
	g++ -Wall -g -o lab_7.cpp
	
lab_8_unit_Test: lab_8_unit_test.cpp
	g++ -Wall -g -c lab_8_unit_test.cpp
	
lab_7_unit_Test: lab_7_unit_test.cpp
	g++ -Wall -g -c lab_7_unit_test.cpp