lab12test:lab_12_unit_test.o magic_item.o food_item.o item.o
	g++ -Wall -g -o lab12test magic_item.o food_item.o item.o lab_12_unit_test.o

lab12_3: magic_item.cpp magic_item.h
	g++ -Wall -g -c magic_item.cpp

lab12_2: food_item.cpp food_item.h
	g++ -Wall -g -c food_item.cpp

lab12_1: item.cpp item.h
	g++ -Wall -g -c item.cpp

lab_12_unit_test: lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp