lab21test: lab_21_unit_test.o bst_node.o
	g++ -Wall -g -o lab21test lab_21_unit_test.o bst_node.o

bst_node: bst_node.cpp bst_node.h
	g++ -Wall -g -c bst_node.cpp

lab_21_unit_test: lab_21_unit_test.cpp
	g++ -Wall -g -c lab_21_unit_test.cpp