assignmenttest: Prize.o Box.o assignment3_unit_test.o
	g++ -Wall -g -o runmain Prize.o Box.o assignment3_unit_test.o

assign_3_unit_test.o: assignment3_unit_test.cpp
	g++ -Wall -g -c assignment3_unit_test.cpp

Pox.o: Box.cpp Box.h
	g++ -Wall -g -c Box.cpp

Prize.o: Prize.cpp Prize.h
	g++ -Wall -g -c Prize.cpp