lab10test:lab_10_unit_test.o temperature.o
	g++ -Wall -g -o lab10test temperature.o lab_10_unit_test.o

lab10: temperature.cpp temperature.h
	g++ -Wall -g -c temperature.cpp

lab_10_unit_test: lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp