lab14test: lab_14_unit_test.o lab_14.o
	g++ -Wall -g -o lab14test lab_14_unit_test.o lab_14.o

lab14: lab_14.cpp lab_14.h
	g++ -Wall -g -c lab_14.cpp

lab_14_unit_test: lab_14_unit_test.cpp
	g++ -Wall -g -c lab_14_unit_test.cpp