lab13test: lab_13_unit_test.o Box.o
	g++ -Wall -g -o lab13test Box.o lab_13_unit_test.o
	
Lab13: Box.h
	g++ -Wall -g -c Box.h
	
lab_13_unit_test: lab_13_unit_test.cpp
	g++ -Wall -g -c lab_13_unit_test.cpp