lab11test: lab_11_unit_test.o money.o
	g++ -Wall -g -o lab11test money.o lab_11_unit_test.o
	
lab11: money.cpp money.h
	g++ -Wall -g -c money.cpp
	
lab_11_unit_test: lab_11_unit_test.cpp
	g++ -Wall -g -c lab_11_unit_test.cpp