lab17test: lab_17_unit_test.o sl_node.o sl_list.o
	g++ -Wall -g -o lab17test lab_17_unit_test.o sl_list.o sl_node.o

lab17_B: sl_list.cpp sl_list.h
	g++ -Wall -g -c sl_list.cpp

lab17_A: sl_node.cpp sl_node.h
	g++ -Wall -g -c sl_node.cpp

lab_17_unit_test: lab_17_unit_test.cpp
	g++ -Wall -g -c lab_17_unit_test.cpp