lab24test: lab_24_unit_test.o sorting.o
	g++ -Wall -g -o lab24test lab_24_unit_test.o sorting.o

sorting: sorting.cpp sorting.h
	g++ -Wall -g -c sorting.cpp

lab_24_unit_test: lab_24_unit_test.cpp
	g++ -Wall -g -c lab_24_unit_test.cpp