lab4test: lab_4_unitTest.o lab_4.o
	g++ -Wall -g -o lab4test lab_4.o lab_4_unitTest.o
	
lab4: lab_4.cpp lab_4.h
	g++ -Wal -g -o lab_4.cpp
	
lab_4_unitTest: lab_4_unitTest.cpp
	g++ -Wall -g -c lab_4_unitTest.cpp