lab18test: lab_18_unit_test.o sl_node.o sl_list.o
	g++ -Wall -g -o lab18test lab_18_unit_test.o sl_list.o sl_node.o

lab18_B: sl_list.cpp sl_list.h
	g++ -Wall -g -c sl_list.cpp

lab18_A: sl_node.cpp sl_node.h
	g++ -Wall -g -c sl_node.cpp

lab_18_unit_test: lab_18_unit_test.cpp
	g++ -Wall -g -c lab_18_unit_test.cpp