lab5test: lab_5_unit_test.o lab_5.o
	g++ -Wall -g -o lab5test lab_5.o lab_5_unit_test.o
	
lab5: lab_5.cpp lab_5.h
	g++ -Wal -g -o lab_5.cpp
	
lab_5_unit_Test: lab_5_unit_test.cpp
	g++ -Wall -g -c lab_5_unit_test.cpp