lab16test: lab_16_unit_test.o sl_node.o sl_list.o
	g++ -Wall -g -o lab16test lab_16_unit_test.o sl_list.o sl_node.o

lab16_B: sl_list.cpp sl_list.h
	g++ -Wall -g -c sl_list.cpp

lab16_A: sl_node.cpp sl_node.h
	g++ -Wall -g -c sl_node.cpp

lab_16_unit_test: lab_16_unit_test.cpp
	g++ -Wall -g -c lab_16_unit_test.cpp