lab20test: lab_20_unit_test.o lab_20.o
	g++ -Wall -g -o lab20test lab_20_unit_test.o lab_20.o

lab_20: lab_20.cpp lab_20.h
	g++ -Wall -g -c lab_20.cpp

lab_20_unit_test: lab_20_unit_test.cpp
	g++ -Wall -g -c lab_20_unit_test.cpp